name: release
on:
  push:
    branches:
      - master
jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(cat ./VERSION)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-oidc-provider:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-oidc-provider:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-oidc-provider:latest
          cache-to: type=inline
          context: ./
          file: ./Dockerfile
